kubeVersion: '>=1.24.0-0'
apiVersion: v2
name: filezilla
version: 8.1.0
appVersion: 3.64.0@sha256:63266abab2a654883d7219c3ee4024cbd6d6c8155e9d9d1e41e0b476d957e244
description: A Helm chart for Kubernetes
home: https://truecharts.org/charts/incubator/filezilla
icon: https://truecharts.org/img/hotlink-ok/chart-icons/filezilla.png
deprecated: false
sources:
    - https://github.com/truecharts/containers/tree/master/mirrorfilezilla
    - https://github.com/linuxserver/docker-filezilla
    - https://filezilla-project.org/
    - https://github.com/truecharts/charts/tree/master/charts/incubator/filezilla
maintainers:
    - name: TrueCharts
      email: info@truecharts.org
      url: https://truecharts.org
keywords:
    - filezilla
    - ftp
    - sftp
    - ftps
    - client
dependencies:
    - name: common
      version: 13.2.2
      repository: https://library-charts.truecharts.org
      condition: ""
      alias: ""
      tags: []
      import-values: []
annotations:
    max_scale_version: 23.10.2
    min_scale_version: 23.10.0
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
    truecharts.org/max_helm_version: "3.13"
    truecharts.org/min_helm_version: "3.12"
    truecharts.org/train: incubator
type: application
