kubeVersion: '>=1.24.0-0'
apiVersion: v2
name: immich
version: 9.2.0
appVersion: 1.91.4@sha256:4f592d059b7f1a5b939933f6dd6a72fb231796710f1daa3203eaef6d2a500b0b
description: High performance self-hosted photo and video backup solution.
home: https://truecharts.org/charts/stable/immich
icon: https://truecharts.org/img/hotlink-ok/chart-icons/immich.png
deprecated: false
sources:
    - https://github.com/immich-app/immich
    - https://github.com/truecharts/charts/tree/master/charts/stable/immich
    - https://hub.docker.com/r/altran1502/immich-server
maintainers:
    - name: TrueCharts
      email: info@truecharts.org
      url: https://truecharts.org
keywords:
    - photos
dependencies:
    - name: common
      version: 14.5.0
      repository: https://library-charts.truecharts.org
      condition: ""
      alias: ""
      tags: []
      import-values: []
    - name: redis
      version: 6.0.66
      repository: https://deps.truecharts.org
      condition: redis.enabled
      alias: ""
      tags: []
      import-values: []
annotations:
    max_scale_version: 23.10.2
    min_scale_version: 23.10.0
    truecharts.org/SCALE-support: "true"
    truecharts.org/category: media
    truecharts.org/max_helm_version: "3.13"
    truecharts.org/min_helm_version: "3.12"
    truecharts.org/train: stable
type: application
